export const POST_LOGIN = 'POST_LOGIN'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const POST_SIGNUP = 'POST_SIGNUP'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'
export const GET_USER_LIST = 'GET_USER_LIST'
export const GET_USER_PROFILE = 'GET_USER_PROFILE'
export const DELETE_USER = 'DELETE_USER'
export const ADMIN_ADD_USER = 'ADMIN_ADD_USER'